sudo: false

env:
  global:
    secure: kRjum2tZsaQZPnti27bc/ZIjYS1hftXTyuSWdq/6raRignORgbZMUc/RMXBz+ig8kiEVE3SFBZdapECGj+3Vb6Q6Vi4ypv8lR4rtJMTNITSOeM1KHHDCi6xLLGKrOsJ5ndkYHTNxuyIMGZu9Sv3TMcNqHcBChbZKT383OXgrxLA=

matrix:
  include:
  - os: osx
    osx_image: xcode6.4
    language: generic
    env: ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: osx
    osx_image: xcode8
    language: generic
    env: ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: osx
    osx_image: xcode8.3
    language: generic
    env: ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: osx
    osx_image: xcode9.3
    language: generic
    env: ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: linux
    language: python
    python: 2.7
    env: ENABLE_LIBSPHINXAD=1
  - os: linux
    language: python
    python: 3.5
    env: ENABLE_LIBSPHINXAD=1
  - os: linux
    language: python
    python: 3.6
    env: ENABLE_LIBSPHINXAD=1 BUILD_SDIST=true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew reinstall swig python python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$HOME/Library/Python/3.6/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y swig libpulse-dev; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python2 -m pip install --user --upgrade pip setuptools wheel twine; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m pip install --user --upgrade pip setuptools wheel twine; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -m pip install --upgrade pip setuptools wheel twine; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python2 setup.py test; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 setup.py test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py test; fi

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$BUILD_SDIST" == "true" ]]; then python2 setup.py sdist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$BUILD_WHEEL" == "true" ]]; then python2 setup.py bdist_wheel; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$BUILD_SDIST" == "true" ]]; then python3 setup.py sdist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$BUILD_WHEEL" == "true" ]]; then python3 setup.py bdist_wheel; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_SDIST" == "true" ]]; then python setup.py sdist; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_WHEEL" == "true" ]]; then python setup.py bdist_wheel; fi

deploy:
  provider: script
  script: twine upload -u bambucha -p $PASSWORD dist/*
  on:
    tags: true
    branch: master
    condition: '"$BUILD_SDIST" == "true" || "$BUILD_WHEEL" == "true"'
  skip_cleanup: true
